server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # SPA 路由回退
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 生产环境把 API/媒体反代到后端容器
    location /api/ {
        proxy_pass http://backend:8000;
    }
    location /media/ {
        proxy_pass http://backend:8000;
    }
}
